# Generated by Django 4.1 on 2023-02-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TStatusBerkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_status_berkas',
                'managed': False,
            },
        ),
    ]
